# coding: utf-8

# Copyright 2026 PT Espay Debit Indonesia Koe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
    Merchant Management API

    API for merchant management operations in DANA

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from dana.base.model import BaseSdkModel

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic import AliasGenerator
from pydantic.alias_generators import to_camel

class AssetCardListItem(BaseModel, BaseSdkModel):
    """
    One row in `assetCardList` (response body)
    """ # noqa: E501
    contact_biz_type: StrictStr = Field(description="Contact business type (`ContactBizTypeEnum`)")
    card_index_no: Annotated[str, Field(strict=True, max_length=20)] = Field(description="Card index number")
    card_no_length: Annotated[str, Field(strict=True, max_length=2)] = Field(description="Card number length based on card index number")
    masked_card_no: Annotated[str, Field(strict=True, max_length=256)] = Field(description="Card number (masked)")
    asset_type: StrictStr = Field(description="Asset / card type (`AssetCardTypeEnum`)")
    holder_name: Dict[str, Any] = Field(description="Holder name (JSON object per DANA spec)")
    inst_logo_url: Optional[StrictStr] = Field(default=None, description="Institution logo URL")
    inst_id: Annotated[str, Field(strict=True, max_length=32)] = Field(description="Institution identifier")
    inst_official_name: Annotated[str, Field(strict=True, max_length=32)] = Field(description="Institution official name based on `instId`")
    expiry_year: Annotated[str, Field(strict=True, max_length=4)] = Field(description="Expiry year (e.g. debit, credit, virtual account)")
    expiry_month: Annotated[str, Field(strict=True, max_length=2)] = Field(description="Expiry month")
    verified: Annotated[str, Field(strict=True, max_length=5)] = Field(description="Whether the user's card is verified")
    binding_id: Optional[Annotated[str, Field(strict=True, max_length=21)]] = Field(default=None, description="Asset card bind identifier")
    default_asset: Optional[Annotated[str, Field(strict=True, max_length=5)]] = Field(default=None, description="Whether this asset is the user's default payment")
    enable_status: Optional[Annotated[str, Field(strict=True, max_length=5)]] = Field(default=None, description="Whether the card status is enabled; `\"true\"` when `enableOnly` in request was true")
    direct_debit: Optional[Annotated[str, Field(strict=True, max_length=5)]] = Field(default=None, description="Whether payment uses direct debit")
    __properties: ClassVar[List[str]] = ["contactBizType", "cardIndexNo", "cardNoLength", "maskedCardNo", "assetType", "holderName", "instLogoUrl", "instId", "instOfficialName", "expiryYear", "expiryMonth", "verified", "bindingId", "defaultAsset", "enableStatus", "directDebit"]

    @field_validator('contact_biz_type')
    def contact_biz_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['TRANSFER_HIS', 'DIRECT_TRANSFER', 'GENERAL_CARD', 'DIRECTPAY_CARD', 'PAYMENT_CARD', 'CASHOUT_CARD', 'IMPS_ACCOUNT', 'INVESTMENT_ACCOUNT']):
            raise ValueError("must be one of enum values ('TRANSFER_HIS', 'DIRECT_TRANSFER', 'GENERAL_CARD', 'DIRECTPAY_CARD', 'PAYMENT_CARD', 'CASHOUT_CARD', 'IMPS_ACCOUNT', 'INVESTMENT_ACCOUNT')")
        return value

    @field_validator('asset_type')
    def asset_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CHECKING_ACCOUNT', 'SAVINGS_ACCOUNT', 'LOAN_ACCOUNT', 'IMPS_ACCOUNT', 'DEBIT_CARD', 'CREDIT_CARD', 'SECURED_CREDIT_CARD', 'VA_ACCOUNT', 'OTC_ACCOUNT', 'REFUND_ACCOUNT', 'CREDIT_ACCOUNT', 'LOAN', 'MUTUAL_FUNDS_ACCOUNT', 'INVESTMENT']):
            raise ValueError("must be one of enum values ('CHECKING_ACCOUNT', 'SAVINGS_ACCOUNT', 'LOAN_ACCOUNT', 'IMPS_ACCOUNT', 'DEBIT_CARD', 'CREDIT_CARD', 'SECURED_CREDIT_CARD', 'VA_ACCOUNT', 'OTC_ACCOUNT', 'REFUND_ACCOUNT', 'CREDIT_ACCOUNT', 'LOAN', 'MUTUAL_FUNDS_ACCOUNT', 'INVESTMENT')")
        return value

    @field_validator('verified')
    def verified_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    @field_validator('default_asset')
    def default_asset_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    @field_validator('enable_status')
    def enable_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    @field_validator('direct_debit')
    def direct_debit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        alias_generator=AliasGenerator(serialization_alias=to_camel, validation_alias=to_camel),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict(), separators=(',', ':'))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetCardListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetCardListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            # If it's a string (JSON), try to parse it
            if isinstance(obj, str):
                try:
                    obj = json.loads(obj)
                except json.JSONDecodeError:
                    return cls.model_validate(obj)
            else:
                return cls.model_validate(obj)

        
        # Handle OPEN_API nested response format: {"response": {"head": {...}, "body": {...}}}
        # Check if this is a response model and has nested structure
        if "AssetCardListItem".endswith("Response") and "response" in obj and "body" in obj["response"]:
            # For OPEN_API nested format, pass the nested response structure directly
            _obj = cls.model_validate({
                "contactBizType": obj.get("contactBizType"),
                "cardIndexNo": obj.get("cardIndexNo"),
                "cardNoLength": obj.get("cardNoLength"),
                "maskedCardNo": obj.get("maskedCardNo"),
                "assetType": obj.get("assetType"),
                "holderName": obj.get("holderName"),
                "instLogoUrl": obj.get("instLogoUrl"),
                "instId": obj.get("instId"),
                "instOfficialName": obj.get("instOfficialName"),
                "expiryYear": obj.get("expiryYear"),
                "expiryMonth": obj.get("expiryMonth"),
                "verified": obj.get("verified"),
                "bindingId": obj.get("bindingId"),
                "defaultAsset": obj.get("defaultAsset"),
                "enableStatus": obj.get("enableStatus"),
                "directDebit": obj.get("directDebit")
            })
        else:
            # For flat format, pass the object as-is
            _obj = cls.model_validate({
                "contactBizType": obj.get("contactBizType"),
                "cardIndexNo": obj.get("cardIndexNo"),
                "cardNoLength": obj.get("cardNoLength"),
                "maskedCardNo": obj.get("maskedCardNo"),
                "assetType": obj.get("assetType"),
                "holderName": obj.get("holderName"),
                "instLogoUrl": obj.get("instLogoUrl"),
                "instId": obj.get("instId"),
                "instOfficialName": obj.get("instOfficialName"),
                "expiryYear": obj.get("expiryYear"),
                "expiryMonth": obj.get("expiryMonth"),
                "verified": obj.get("verified"),
                "bindingId": obj.get("bindingId"),
                "defaultAsset": obj.get("defaultAsset"),
                "enableStatus": obj.get("enableStatus"),
                "directDebit": obj.get("directDebit")
            })
        
        return _obj


