# coding: utf-8

# Copyright 2026 PT Espay Debit Indonesia Koe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
    Merchant Management API

    API for merchant management operations in DANA

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from dana.base.model import BaseSdkModel

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from dana.merchant_management.v1.models.merchant_account_info import MerchantAccountInfo
from dana.merchant_management.v1.models.merchant_certificate_info import MerchantCertificateInfo
from dana.merchant_management.v1.models.merchant_contact_address import MerchantContactAddress
from dana.merchant_management.v1.models.merchant_contact_email import MerchantContactEmail
from dana.merchant_management.v1.models.merchant_contact_mobile_no import MerchantContactMobileNo
from dana.merchant_management.v1.models.merchant_corporate_certificate import MerchantCorporateCertificate
from dana.merchant_management.v1.models.user_name import UserName
from typing import Optional, Set
from typing_extensions import Self
from pydantic import AliasGenerator
from pydantic.alias_generators import to_camel

class MerchantInformation(BaseModel, BaseSdkModel):
    """
    Merchant profile detail (`merchantInformation` in response body)
    """ # noqa: E501
    phone_number: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Phone number")
    merchant_id: Optional[Annotated[str, Field(strict=True, max_length=21)]] = Field(default=None, description="Merchant identifier")
    merchant_type: Optional[Annotated[str, Field(strict=True, max_length=14)]] = Field(default=None, description="Merchant type")
    merchant_sub_type: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="Merchant sub type")
    mcc_codes: Optional[List[Annotated[str, Field(strict=True, max_length=64)]]] = Field(default=None, description="Merchant category codes (MCC)")
    logo_url: Optional[StrictStr] = Field(default=None, description="Logo URL")
    logo_url_map: Optional[Dict[str, StrictStr]] = Field(default=None, description="Logo map. Keys may be `LOGO`, `PC_LOGO`, `MOBILE_LOGO`. Values are base64-encoded PNG image data. ")
    short_name_code: Optional[Annotated[str, Field(strict=True, max_length=16)]] = Field(default=None, description="Merchant short name code")
    official_name: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Merchant official name")
    english_name: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Merchant English name")
    local_name: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Merchant local (Indonesian) name")
    certificate: Optional[MerchantCertificateInfo] = None
    registered_address: Optional[MerchantContactAddress] = Field(default=None)
    business_address: Optional[MerchantContactAddress] = Field(default=None)
    office_telephone: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Merchant official telephone number")
    fax_telephone: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Merchant official fax telephone number")
    corporate_official_name: Optional[UserName] = Field(default=None)
    corporate_certificate: Optional[MerchantCorporateCertificate] = Field(default=None)
    contact_official_name: Optional[UserName] = Field(default=None)
    contact_mobile_no: Optional[MerchantContactMobileNo] = Field(default=None)
    contact_telephone: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="Contact telephone number")
    contact_email: Optional[MerchantContactEmail] = Field(default=None)
    created_time: Optional[Annotated[str, Field(strict=True, max_length=25)]] = Field(default=None, description="Merchant creation time, YYYY-MM-DDTHH:mm:ss+07:00 (GMT+7)")
    modified_time: Optional[Annotated[str, Field(strict=True, max_length=25)]] = Field(default=None, description="Merchant last modified time, YYYY-MM-DDTHH:mm:ss+07:00 (GMT+7)")
    merchant_status: Optional[Annotated[str, Field(strict=True, max_length=7)]] = Field(default=None, description="Merchant status")
    register_source: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Registered source platform")
    size_type: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default=None, description="Size type")
    platform_mid: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Merchant platform identifier")
    tax_no: Optional[Annotated[str, Field(strict=True, max_length=15)]] = Field(default=None, description="Tax number (NPWP), 15 digits")
    accounts: Optional[List[MerchantAccountInfo]] = Field(default=None, description="Merchant account list (present when `isQueryAccount` is true in request)")
    brand_name: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Brand name on legal name or tax name")
    tax_address: Optional[MerchantContactAddress] = Field(default=None)
    __properties: ClassVar[List[str]] = ["phoneNumber", "merchantId", "merchantType", "merchantSubType", "mccCodes", "logoUrl", "logoUrlMap", "shortNameCode", "officialName", "englishName", "localName", "certificate", "registeredAddress", "businessAddress", "officeTelephone", "faxTelephone", "corporateOfficialName", "corporateCertificate", "contactOfficialName", "contactMobileNo", "contactTelephone", "contactEmail", "createdTime", "modifiedTime", "merchantStatus", "registerSource", "sizeType", "platformMid", "taxNo", "accounts", "brandName", "taxAddress"]

    @field_validator('merchant_type')
    def merchant_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INDIVIDUAL', 'CORPORATION', 'FINANCIAL_INST']):
            raise ValueError("must be one of enum values ('INDIVIDUAL', 'CORPORATION', 'FINANCIAL_INST')")
        return value

    @field_validator('merchant_sub_type')
    def merchant_sub_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['COMPANY_TYPE_22', 'COMPANY_TYPE_31', 'COMPANY_TYPE_41']):
            raise ValueError("must be one of enum values ('COMPANY_TYPE_22', 'COMPANY_TYPE_31', 'COMPANY_TYPE_41')")
        return value

    @field_validator('merchant_status')
    def merchant_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PENDING', 'ACTIVE', 'FROZEN']):
            raise ValueError("must be one of enum values ('PENDING', 'ACTIVE', 'FROZEN')")
        return value

    @field_validator('size_type')
    def size_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['UMI', 'UKE', 'UME', 'UBE', 'URE']):
            raise ValueError("must be one of enum values ('UMI', 'UKE', 'UME', 'UBE', 'URE')")
        return value

    @field_validator('tax_no')
    def tax_no_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9]{15}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]{15}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        alias_generator=AliasGenerator(serialization_alias=to_camel, validation_alias=to_camel),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict(), separators=(',', ':'))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantInformation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of certificate
        if self.certificate:
            _dict['certificate'] = self.certificate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of registered_address
        if self.registered_address:
            _dict['registeredAddress'] = self.registered_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of business_address
        if self.business_address:
            _dict['businessAddress'] = self.business_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of corporate_official_name
        if self.corporate_official_name:
            _dict['corporateOfficialName'] = self.corporate_official_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of corporate_certificate
        if self.corporate_certificate:
            _dict['corporateCertificate'] = self.corporate_certificate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_official_name
        if self.contact_official_name:
            _dict['contactOfficialName'] = self.contact_official_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_mobile_no
        if self.contact_mobile_no:
            _dict['contactMobileNo'] = self.contact_mobile_no.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_email
        if self.contact_email:
            _dict['contactEmail'] = self.contact_email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of tax_address
        if self.tax_address:
            _dict['taxAddress'] = self.tax_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantInformation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            # If it's a string (JSON), try to parse it
            if isinstance(obj, str):
                try:
                    obj = json.loads(obj)
                except json.JSONDecodeError:
                    return cls.model_validate(obj)
            else:
                return cls.model_validate(obj)

        
        # Handle OPEN_API nested response format: {"response": {"head": {...}, "body": {...}}}
        # Check if this is a response model and has nested structure
        if "MerchantInformation".endswith("Response") and "response" in obj and "body" in obj["response"]:
            # For OPEN_API nested format, pass the nested response structure directly
            _obj = cls.model_validate({
                "phoneNumber": obj.get("phoneNumber"),
                "merchantId": obj.get("merchantId"),
                "merchantType": obj.get("merchantType"),
                "merchantSubType": obj.get("merchantSubType"),
                "mccCodes": obj.get("mccCodes"),
                "logoUrl": obj.get("logoUrl"),
                "logoUrlMap": obj.get("logoUrlMap"),
                "shortNameCode": obj.get("shortNameCode"),
                "officialName": obj.get("officialName"),
                "englishName": obj.get("englishName"),
                "localName": obj.get("localName"),
                "certificate": MerchantCertificateInfo.from_dict(obj["certificate"]) if obj.get("certificate") is not None else None,
                "registeredAddress": MerchantContactAddress.from_dict(obj["registeredAddress"]) if obj.get("registeredAddress") is not None else None,
                "businessAddress": MerchantContactAddress.from_dict(obj["businessAddress"]) if obj.get("businessAddress") is not None else None,
                "officeTelephone": obj.get("officeTelephone"),
                "faxTelephone": obj.get("faxTelephone"),
                "corporateOfficialName": UserName.from_dict(obj["corporateOfficialName"]) if obj.get("corporateOfficialName") is not None else None,
                "corporateCertificate": MerchantCorporateCertificate.from_dict(obj["corporateCertificate"]) if obj.get("corporateCertificate") is not None else None,
                "contactOfficialName": UserName.from_dict(obj["contactOfficialName"]) if obj.get("contactOfficialName") is not None else None,
                "contactMobileNo": MerchantContactMobileNo.from_dict(obj["contactMobileNo"]) if obj.get("contactMobileNo") is not None else None,
                "contactTelephone": obj.get("contactTelephone"),
                "contactEmail": MerchantContactEmail.from_dict(obj["contactEmail"]) if obj.get("contactEmail") is not None else None,
                "createdTime": obj.get("createdTime"),
                "modifiedTime": obj.get("modifiedTime"),
                "merchantStatus": obj.get("merchantStatus"),
                "registerSource": obj.get("registerSource"),
                "sizeType": obj.get("sizeType"),
                "platformMid": obj.get("platformMid"),
                "taxNo": obj.get("taxNo"),
                "accounts": [MerchantAccountInfo.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
                "brandName": obj.get("brandName"),
                "taxAddress": MerchantContactAddress.from_dict(obj["taxAddress"]) if obj.get("taxAddress") is not None else None
            })
        else:
            # For flat format, pass the object as-is
            _obj = cls.model_validate({
                "phoneNumber": obj.get("phoneNumber"),
                "merchantId": obj.get("merchantId"),
                "merchantType": obj.get("merchantType"),
                "merchantSubType": obj.get("merchantSubType"),
                "mccCodes": obj.get("mccCodes"),
                "logoUrl": obj.get("logoUrl"),
                "logoUrlMap": obj.get("logoUrlMap"),
                "shortNameCode": obj.get("shortNameCode"),
                "officialName": obj.get("officialName"),
                "englishName": obj.get("englishName"),
                "localName": obj.get("localName"),
                "certificate": MerchantCertificateInfo.from_dict(obj["certificate"]) if obj.get("certificate") is not None else None,
                "registeredAddress": MerchantContactAddress.from_dict(obj["registeredAddress"]) if obj.get("registeredAddress") is not None else None,
                "businessAddress": MerchantContactAddress.from_dict(obj["businessAddress"]) if obj.get("businessAddress") is not None else None,
                "officeTelephone": obj.get("officeTelephone"),
                "faxTelephone": obj.get("faxTelephone"),
                "corporateOfficialName": UserName.from_dict(obj["corporateOfficialName"]) if obj.get("corporateOfficialName") is not None else None,
                "corporateCertificate": MerchantCorporateCertificate.from_dict(obj["corporateCertificate"]) if obj.get("corporateCertificate") is not None else None,
                "contactOfficialName": UserName.from_dict(obj["contactOfficialName"]) if obj.get("contactOfficialName") is not None else None,
                "contactMobileNo": MerchantContactMobileNo.from_dict(obj["contactMobileNo"]) if obj.get("contactMobileNo") is not None else None,
                "contactTelephone": obj.get("contactTelephone"),
                "contactEmail": MerchantContactEmail.from_dict(obj["contactEmail"]) if obj.get("contactEmail") is not None else None,
                "createdTime": obj.get("createdTime"),
                "modifiedTime": obj.get("modifiedTime"),
                "merchantStatus": obj.get("merchantStatus"),
                "registerSource": obj.get("registerSource"),
                "sizeType": obj.get("sizeType"),
                "platformMid": obj.get("platformMid"),
                "taxNo": obj.get("taxNo"),
                "accounts": [MerchantAccountInfo.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
                "brandName": obj.get("brandName"),
                "taxAddress": MerchantContactAddress.from_dict(obj["taxAddress"]) if obj.get("taxAddress") is not None else None
            })
        
        return _obj


