# coding: utf-8

# Copyright 2026 PT Espay Debit Indonesia Koe
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# flake8: noqa

"""
    Merchant Management API

    API for merchant management operations in DANA

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from dana.merchant_management.v1.api.merchant_management_api import MerchantManagementApi


# import models into sdk package
from dana.merchant_management.v1.models.address_info import AddressInfo
from dana.merchant_management.v1.models.asset_card_list_item import AssetCardListItem
from dana.merchant_management.v1.models.business_docs import BusinessDocs
from dana.merchant_management.v1.models.create_division_request import CreateDivisionRequest
from dana.merchant_management.v1.models.create_division_request_ext_info import CreateDivisionRequestExtInfo
from dana.merchant_management.v1.models.create_division_response import CreateDivisionResponse
from dana.merchant_management.v1.models.create_division_response_response import CreateDivisionResponseResponse
from dana.merchant_management.v1.models.create_division_response_response_body import CreateDivisionResponseResponseBody
from dana.merchant_management.v1.models.create_division_response_response_head import CreateDivisionResponseResponseHead
from dana.merchant_management.v1.models.create_shop_request import CreateShopRequest
from dana.merchant_management.v1.models.create_shop_response import CreateShopResponse
from dana.merchant_management.v1.models.create_shop_response_response import CreateShopResponseResponse
from dana.merchant_management.v1.models.create_shop_response_response_body import CreateShopResponseResponseBody
from dana.merchant_management.v1.models.create_shop_response_response_head import CreateShopResponseResponseHead
from dana.merchant_management.v1.models.division_resource_info import DivisionResourceInfo
from dana.merchant_management.v1.models.member_asset_result_info import MemberAssetResultInfo
from dana.merchant_management.v1.models.merchant_account_info import MerchantAccountInfo
from dana.merchant_management.v1.models.merchant_certificate_info import MerchantCertificateInfo
from dana.merchant_management.v1.models.merchant_contact_address import MerchantContactAddress
from dana.merchant_management.v1.models.merchant_contact_email import MerchantContactEmail
from dana.merchant_management.v1.models.merchant_contact_mobile_no import MerchantContactMobileNo
from dana.merchant_management.v1.models.merchant_corporate_certificate import MerchantCorporateCertificate
from dana.merchant_management.v1.models.merchant_information import MerchantInformation
from dana.merchant_management.v1.models.merchant_resource_information import MerchantResourceInformation
from dana.merchant_management.v1.models.mobile_no_info import MobileNoInfo
from dana.merchant_management.v1.models.pic_info import PicInfo
from dana.merchant_management.v1.models.query_asset_card_list_request import QueryAssetCardListRequest
from dana.merchant_management.v1.models.query_asset_card_list_response import QueryAssetCardListResponse
from dana.merchant_management.v1.models.query_asset_card_list_response_response import QueryAssetCardListResponseResponse
from dana.merchant_management.v1.models.query_asset_card_list_response_response_body import QueryAssetCardListResponseResponseBody
from dana.merchant_management.v1.models.query_asset_card_list_response_response_head import QueryAssetCardListResponseResponseHead
from dana.merchant_management.v1.models.query_division_request import QueryDivisionRequest
from dana.merchant_management.v1.models.query_division_response import QueryDivisionResponse
from dana.merchant_management.v1.models.query_division_response_response import QueryDivisionResponseResponse
from dana.merchant_management.v1.models.query_division_response_response_body import QueryDivisionResponseResponseBody
from dana.merchant_management.v1.models.query_division_response_response_head import QueryDivisionResponseResponseHead
from dana.merchant_management.v1.models.query_merchant_info_request import QueryMerchantInfoRequest
from dana.merchant_management.v1.models.query_merchant_info_response import QueryMerchantInfoResponse
from dana.merchant_management.v1.models.query_merchant_info_response_response import QueryMerchantInfoResponseResponse
from dana.merchant_management.v1.models.query_merchant_info_response_response_body import QueryMerchantInfoResponseResponseBody
from dana.merchant_management.v1.models.query_merchant_info_response_response_head import QueryMerchantInfoResponseResponseHead
from dana.merchant_management.v1.models.query_merchant_resource_request import QueryMerchantResourceRequest
from dana.merchant_management.v1.models.query_merchant_resource_response import QueryMerchantResourceResponse
from dana.merchant_management.v1.models.query_merchant_resource_response_response import QueryMerchantResourceResponseResponse
from dana.merchant_management.v1.models.query_merchant_resource_response_response_body import QueryMerchantResourceResponseResponseBody
from dana.merchant_management.v1.models.query_merchant_resource_response_response_head import QueryMerchantResourceResponseResponseHead
from dana.merchant_management.v1.models.query_shop_request import QueryShopRequest
from dana.merchant_management.v1.models.query_shop_response import QueryShopResponse
from dana.merchant_management.v1.models.query_shop_response_response import QueryShopResponseResponse
from dana.merchant_management.v1.models.query_shop_response_response_body import QueryShopResponseResponseBody
from dana.merchant_management.v1.models.query_shop_response_response_head import QueryShopResponseResponseHead
from dana.merchant_management.v1.models.result_info import ResultInfo
from dana.merchant_management.v1.models.shop_resource_info import ShopResourceInfo
from dana.merchant_management.v1.models.update_division_request import UpdateDivisionRequest
from dana.merchant_management.v1.models.update_division_response import UpdateDivisionResponse
from dana.merchant_management.v1.models.update_division_response_response import UpdateDivisionResponseResponse
from dana.merchant_management.v1.models.update_division_response_response_body import UpdateDivisionResponseResponseBody
from dana.merchant_management.v1.models.update_division_response_response_head import UpdateDivisionResponseResponseHead
from dana.merchant_management.v1.models.update_shop_request import UpdateShopRequest
from dana.merchant_management.v1.models.update_shop_response import UpdateShopResponse
from dana.merchant_management.v1.models.update_shop_response_response import UpdateShopResponseResponse
from dana.merchant_management.v1.models.update_shop_response_response_head import UpdateShopResponseResponseHead
from dana.merchant_management.v1.models.user_name import UserName
